import { FieldDefinition } from "@/types";

export interface ValidationResult {
  isValid: boolean;
  errors: Record<string, string>;
}

export function validateFormData(
  fields: FieldDefinition[],
  data: Record<string, any>
): ValidationResult {
  const errors: Record<string, string> = {};

  for (const field of fields) {
    const val = data[field.name];

    // Check required
    if (field.required) {
      if (val === undefined || val === null || val === "") {
        errors[field.name] = `${field.label} is required.`;
        continue;
      }
    }

    if (val !== undefined && val !== null && val !== "") {
      // Type specific checks
      if (field.type === "number") {
        const num = Number(val);
        if (isNaN(num)) {
          errors[field.name] = `${field.label} must be a valid number.`;
        } else if (field.validation?.min !== undefined && num < field.validation.min) {
          errors[field.name] = `${field.label} must be at least ${field.validation.min}.`;
        } else if (field.validation?.max !== undefined && num > field.validation.max) {
          errors[field.name] = `${field.label} cannot exceed ${field.validation.max}.`;
        }
      } else if (field.type === "email") {
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(String(val))) {
          errors[field.name] = `Please enter a valid email address for ${field.label}.`;
        }
      } else if (field.type === "text" || field.type === "textarea") {
        const str = String(val);
        if (field.validation?.min !== undefined && str.length < field.validation.min) {
          errors[field.name] = `${field.label} must be at least ${field.validation.min} characters.`;
        } else if (field.validation?.max !== undefined && str.length > field.validation.max) {
          errors[field.name] = `${field.label} must be no more than ${field.validation.max} characters.`;
        }
      }
    }
  }

  return {
    isValid: Object.keys(errors).length === 0,
    errors,
  };
}

export function interpolateTemplate(
  templateContent: string,
  data: Record<string, any>
): string {
  let content = templateContent;

  // Process conditional blocks: {{#if key}}...{{/if}}
  content = content.replace(
    /\{\{#if\s+([a-zA-Z0-9_]+)\}\}([\s\S]*?)\{\{\/if\}\}/g,
    (_, key, block) => {
      const val = data[key];
      if (val && val !== "false" && val !== "0" && val !== false) {
        return block;
      }
      return "";
    }
  );

  // Process inverted conditional blocks: {{#unless key}}...{{/unless}}
  content = content.replace(
    /\{\{#unless\s+([a-zA-Z0-9_]+)\}\}([\s\S]*?)\{\{\/unless\}\}/g,
    (_, key, block) => {
      const val = data[key];
      if (!val || val === "false" || val === "0" || val === false) {
        return block;
      }
      return "";
    }
  );

  // Process standard placeholders: {{key}}
  content = content.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (_, key) => {
    const val = data[key];
    if (val === undefined || val === null || val === "") {
      return `[${key}]`;
    }
    if (typeof val === "boolean") {
      return val ? "Yes" : "No";
    }
    return String(val);
  });

  return content;
}

export const LEGAL_DISCLAIMER_TEXT =
  "IMPORTANT NOTICE & DISCLAIMER: Documents generated by this platform are general/pre-legal templates for informational purposes only and do not constitute legal advice. Users should consult a qualified legal professional for advice specific to their jurisdiction and situation.";
