import React from "react";
import { AlertTriangle, ShieldCheck } from "lucide-react";
import { cn } from "@/lib/utils";

export interface DisclaimerBannerProps {
  variant?: "warning" | "compact" | "subtle";
  className?: string;
}

export function DisclaimerBanner({
  variant = "warning",
  className,
}: DisclaimerBannerProps) {
  if (variant === "compact") {
    return (
      <div
        className={cn(
          "flex items-center gap-2 p-2.5 rounded-lg bg-amber-50/80 border border-amber-200/80 text-xs text-amber-900",
          className
        )}
      >
        <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
        <p>
          <strong className="font-semibold">Educational / Pre-Legal Draft:</strong>{" "}
          This document is generated from a general template for informational purposes only and is not legal advice. Consult a qualified attorney for jurisdiction-specific legal counsel.
        </p>
      </div>
    );
  }

  if (variant === "subtle") {
    return (
      <div
        className={cn(
          "text-xs text-slate-500 flex items-center gap-1.5",
          className
        )}
      >
        <ShieldCheck className="w-3.5 h-3.5 text-slate-400 shrink-0" />
        <span>Pre-legal informational template | Not a substitute for formal legal advice</span>
      </div>
    );
  }

  return (
    <div
      className={cn(
        "rounded-xl border border-amber-200 bg-amber-50/90 p-4 text-amber-950 flex items-start gap-3.5 shadow-sm",
        className
      )}
    >
      <div className="p-1.5 bg-amber-100 rounded-lg text-amber-700 shrink-0 mt-0.5">
        <AlertTriangle className="w-5 h-5" />
      </div>
      <div className="space-y-1">
        <h4 className="text-sm font-semibold text-amber-900">
          Important Legal Notice & Educational Disclaimer
        </h4>
        <p className="text-xs leading-relaxed text-amber-800">
          Documents generated by this platform are general/pre-legal templates for informational purposes only and do not constitute legal advice. Users should consult a qualified legal professional for advice specific to their situation and jurisdiction before executing or filing legal agreements.
        </p>
      </div>
    </div>
  );
}
