import React from "react";
import Link from "next/link";
import { Shield, AlertCircle, FileText } from "lucide-react";

export function Footer() {
  return (
    <footer className="bg-slate-900 text-slate-300 pt-16 pb-12 border-t border-slate-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        {/* Top Grid */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-10">
          {/* Brand Col */}
          <div className="md:col-span-1 space-y-4">
            <Link href="/" className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-lg bg-blue-600 text-white flex items-center justify-center">
                <Shield className="w-4 h-4" />
              </div>
              <span className="text-lg font-bold tracking-tight text-white">
                PreLegal<span className="text-blue-400">Doc</span>
              </span>
            </Link>
            <p className="text-xs text-slate-400 leading-relaxed">
              Fast, structured, and accessible pre-legal document creation designed for individuals, freelancers, and small business owners.
            </p>
          </div>

          {/* Column: Platform */}
          <div>
            <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-200 mb-4">
              Platform
            </h4>
            <ul className="space-y-2.5 text-xs text-slate-400">
              <li>
                <Link href="/templates" className="hover:text-white transition">
                  Browse All Templates
                </Link>
              </li>
              <li>
                <Link href="/how-it-works" className="hover:text-white transition">
                  How It Works
                </Link>
              </li>
              <li>
                <Link href="/faq" className="hover:text-white transition">
                  Frequently Asked Questions
                </Link>
              </li>
              <li>
                <Link href="/dashboard" className="hover:text-white transition">
                  User Dashboard
                </Link>
              </li>
            </ul>
          </div>

          {/* Column: Document Categories */}
          <div>
            <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-200 mb-4">
              Categories
            </h4>
            <ul className="space-y-2.5 text-xs text-slate-400">
              <li>
                <Link href="/templates?category=real-estate" className="hover:text-white transition">
                  Real Estate & Leases
                </Link>
              </li>
              <li>
                <Link href="/templates?category=business" className="hover:text-white transition">
                  Business & NDA Contracts
                </Link>
              </li>
              <li>
                <Link href="/templates?category=employment" className="hover:text-white transition">
                  Employment Agreements
                </Link>
              </li>
              <li>
                <Link href="/templates?category=personal-legal" className="hover:text-white transition">
                  Affidavits & Letters
                </Link>
              </li>
              <li>
                <Link href="/templates?category=finance" className="hover:text-white transition">
                  Payment & Loan Plans
                </Link>
              </li>
            </ul>
          </div>

          {/* Column: Legal & Disclaimer */}
          <div>
            <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-200 mb-4">
              Compliance
            </h4>
            <ul className="space-y-2.5 text-xs text-slate-400">
              <li>
                <Link href="/about" className="hover:text-white transition">
                  About the Project
                </Link>
              </li>
              <li>
                <span className="text-slate-400">Academic & Educational SaaS</span>
              </li>
              <li>
                <span className="text-slate-400">Standard Pre-Legal Drafts</span>
              </li>
            </ul>
          </div>
        </div>

        {/* Mandatory Legal Disclaimer Section */}
        <div className="rounded-xl border border-slate-800 bg-slate-950/60 p-5 space-y-2">
          <div className="flex items-center gap-2 text-amber-400 text-xs font-semibold">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>IMPORTANT LEGAL DISCLAIMER & SCOPE OF USE</span>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed">
            Documents generated by this platform are general/pre-legal templates for informational purposes only and do not constitute legal advice. Users should consult a qualified legal professional for advice specific to their situation, jurisdiction, and governing regulations. PreLegalDoc is an automated pre-drafting platform and is not a law firm.
          </p>
        </div>

        {/* Copyright and Bottom Meta */}
        <div className="pt-6 border-t border-slate-800/80 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-500 gap-4">
          <p>© {new Date().getFullYear()} PreLegalDoc Generator. Academic SaaS Assignment. All rights reserved.</p>
          <div className="flex items-center gap-4">
            <Link href="/about" className="hover:text-slate-400 transition">
              About Project
            </Link>
            <Link href="/faq" className="hover:text-slate-400 transition">
              FAQ
            </Link>
          </div>
        </div>
      </div>
    </footer>
  );
}
